baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Project Hub"
canonifyURLs = false

# Enable watching for fast dev reload
enableLiveReload = true
enableGitInfo = false

# Taxonomies
[taxonomies]
  status = "status"
  tag = "tags"

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["HTML"]
