# Bootstrap
[bootstrap]
  javascript = true

# PostCSS
[postCSS]
  state = false
  writeStats = true

# Header
[header]
  state = true
  brandLogo = false
  brandText = true
  fixedTop = true

# Banner
[banner]
  home = true
  section = true
  single = false

# Sidebar
[sidebar]
  home = false
  section = false
  single = true
  tableofcontentsID = 'sidebar-tableofcontents'

# Breadcrumbs
[breadcrumb]
  home = false
  homeIcon = 'folder-root'
  section = false
  single = true

# Heading
[heading]
  home = false
  section = false
  single = true

# Footer
[footer]
  state = true
  stick = true

# Copyright
[copyright]
  name = 'Times'
  link = ''
  year = '2024'

# Logo
[logo]
  mainPNG = 'img/logo/logo.png'
  brandPNG = 'img/logo/brand.png'

# Manifest
[manifest]
  state = true
  background = "#333"
